name: rizin-extras 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install python
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools python3-dev ninja-build
    - name: Install meson and ninja
      run: sudo pip3 install meson PyYAML ninja pytest virtualenv
    - uses: actions/checkout@v2
    - name: Install Rizin
      run: |
          git clone --depth=1 https://github.com/rizinorg/rizin
          cd rizin
          meson --buildtype=release --prefix=/usr build
          ninja -C build
          sudo ninja -C build install
          cd ..
    - name: Install rz-svd
      run: |
          cd rz-svd
          meson --buildtype=release --prefix=/usr build
          ninja -C build
          sudo ninja -C build install
          rizin -qc "Lc" | grep rz-svd
          cd ..